import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
shell = "/usr/bin/fish"

[window]
padding = {x = 15, y = 15}

[font]
normal = {family = "JetBrainsMono Nerd Font", style = "Regular"}
size = 15
